apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: angular-frontend
  annotations:
    autoscaling.knative.dev/min-scale: "5"
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: angular-frontend
    apps.tanzu.vmware.com/has-tests: "true"
    apis.apps.tanzu.vmware.com/register-api: "true"
spec:
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: clusterBuilder
      value: full
    - name: api_descriptor
      value:
        type: openapi
        location:
          path: "/v3/api-docs"
  build:
    env:
      - name: BP_NODE_RUN_SCRIPTS
        value: "build"
      - name: BP_WEB_SERVER_ROOT
        value: "dist"
  source:
    git:
      url: https://github.com/dsharmaa4/angular-frontend.git
      ref:
        branch: master
